apiVersion: v1
data:
  cacert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlIbmpDQ0JZYWdBd0lCQWdJUkFKUXpjQ2l3WXJLQ3NOdmRDek5SeU9Fd0RRWUpLb1pJaHZjTkFRRU1CUUF3DQpSREVMTUFrR0ExVUVCaE1DVGt3eEdUQVhCZ05WQkFvVEVFZEZRVTVVSUZabGNtVnVhV2RwYm1jeEdqQVlCZ05WDQpCQU1URVVkRlFVNVVJRTlXSUZKVFFTQkRRU0EwTUI0WERUSTBNRGd4TkRBd01EQXdNRm9YRFRJMU1EZ3hOREl6DQpOVGsxT1Zvd1pERUxNQWtHQTFVRUJoTUNSVk14RWpBUUJnTlZCQWdUQ1VKaGNtTmxiRzl1WVRFb01DWUdBMVVFDQpDaE1mUW1GeVkyVnNiMjVoSUZOMWNHVnlZMjl0Y0hWMGFXNW5JRU5sYm5SbGNqRVhNQlVHQTFVRUF4TU9ibU5zDQpiM1ZrTWk1aWMyTXVaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzJVT1N5DQpUbFVUQ1l4ZHppU3QvRk55ajhaK0p3aWxkV1czZ3pmeVRLeklwR2dXVEpRWUhwUGE1OU9MbkRoYVZObWx0QWNvDQo5eUN3NnNyTjJZUGdRVkNjZ0xZSGdFODZ4VGZtWEh6YTl0bUM5NjhmcW0xZ01EWmtzT29WelV4dDJDWFdoNWtuDQovcmd1VEFVc3cwejgybGprTVBYTTBLb3VkWmpCL2c3QmFzd3Z4WUhkaWNrVkF2c0pQdEN0cVJ1NlI4dzkvMXBKDQpoa2dHNWZkU2gzL3c5dGF3TGpRay95b1NMSDVWYnE3Zllya2U3bEpyWVVnOWpOaTNjTExYZEd2L1VSVmM5Z2htDQpRZkhDYjBnN1cwNEpzZzcxQzcwcFMwcjl3WWw4TGFlQlU2Vm5mM3ZXUWQ2QjFKSlpyL0J3SmFHV3ZoTXBnRXc3DQpQN1RJdkRKTy9lZ21aVzlWQWdNQkFBR2pnZ05wTUlJRFpUQWZCZ05WSFNNRUdEQVdnQlJ2SFRWSkVHd3krbG1nDQpucnlLNkIrVnZuRjZEREFkQmdOVkhRNEVGZ1FVWFZlSnZYRFFvcU0xUzJIVUFEUWpScSt0Mm9Vd0RnWURWUjBQDQpBUUgvQkFRREFnV2dNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHDQpBUVVGQndNQ01Fa0dBMVVkSUFSQ01FQXdOQVlMS3dZQkJBR3lNUUVDQWs4d0pUQWpCZ2dyQmdFRkJRY0NBUllYDQphSFIwY0hNNkx5OXpaV04wYVdkdkxtTnZiUzlEVUZNd0NBWUdaNEVNQVFJQ01EOEdBMVVkSHdRNE1EWXdOS0F5DQpvRENHTG1oMGRIQTZMeTlIUlVGT1ZDNWpjbXd1YzJWamRHbG5ieTVqYjIwdlIwVkJUbFJQVmxKVFFVTkJOQzVqDQpjbXd3ZFFZSUt3WUJCUVVIQVFFRWFUQm5NRG9HQ0NzR0FRVUZCekFDaGk1b2RIUndPaTh2UjBWQlRsUXVZM0owDQpMbk5sWTNScFoyOHVZMjl0TDBkRlFVNVVUMVpTVTBGRFFUUXVZM0owTUNrR0NDc0dBUVVGQnpBQmhoMW9kSFJ3DQpPaTh2UjBWQlRsUXViMk56Y0M1elpXTjBhV2R2TG1OdmJUQ0NBWDhHQ2lzR0FRUUIxbmtDQkFJRWdnRnZCSUlCDQphd0ZwQUhjQTNkektOSlhYNFJZRjU1VXkrc2VmK0QwY1VOL2JBRG9VRW5ZS0xLeTd5Q29BQUFHUlQvMjhzd0FBDQpCQU1BU0RCR0FpRUFsL015UnFpcXJJb2xMNXE0YzhrMzNDajBsNXhTQlQ0R2M4OE5pbVREaFVFQ0lRQzEvTFBWDQpseDdXUVpnMHZLQUhjWmdJcGFYeUw2UnN5T0k1OWdQYWdaV2Q4UUIyQUEzaDhqQXIwdzNCUUdJU0NlcFZMdnhIDQpkSHl4MStrdzd3NUNIclIrVHFvMEFBQUJrVS85dkpJQUFBUURBRWN3UlFJZ0NqRXBjdnlmNnBUY0pCZmJLV1A0DQoxNVp5M1lHWkZHWXd6NlJ5NGN6Y1REa0NJUUNMejIxRkVrMkZNb1g5OWx3NkN1MlJRZlRDVExzMVdnWjc1U2pwDQpSbzlmOEFCMkFCTHhUalM5VTNKTWhBWVp3NDgvZWhQNDU3VmloNGljYlRBRmhPdmxoaVk2QUFBQmtVLzl2S0VBDQpBQVFEQUVjd1JRSWhBTEN4TlZDR0FRcUIrcm43QldTaTg0azh6U1p1b3UrZzRuck5hS3kyNjdicUFpQXpKSEtZDQpZc0FseUNTd2IyUVJtMGZ2K2NJR2hNdExVRkE5RElNeDhNKzd1akJnQmdOVkhSRUVXVEJYZ2c1dVkyeHZkV1F5DQpMbUp6WXk1bGM0SU5ibU5zYjNWa0xtSnpZeTVsYzRJVWJtTnNiM1ZrTWkxaFpHMXBiaTVpYzJNdVpYT0NFbTVqDQpiRzkxWkRJdGFXNTBMbUp6WXk1bGM0SU1jM2RwWm5RdVluTmpMbVZ6TUEwR0NTcUdTSWIzRFFFQkRBVUFBNElDDQpBUUFmcUgvOTh2T1hnbzZiSEl6TE9Cc3kzdmg2LzRwakhtQ3U4Q3BranRIb1hqVmFaZzlLWmF6MmZvNnBHd0hzDQppd2hZTm43UXNMQ200MUZBZkkrR1dkazFQcythNVdSU2Q0Kzg4SnpUZktGejRaQXdOVVFQeEhxcnZyVE1UcElvDQpybU94bFZ3RVpNd0xQbmpHWkk5Tkl3SE5qem83YWY0TzBhODNYWVZsLytnTHdBY1NwN0ZIRGt0TitwbUJLNjFFDQpQWXZnbTNEZTdhTVdHVzgzbGJSSi9KWHkra3daR0d3ZnFuMEtuT3lIZnEvaFQ4SCtCTEMwYUdsQlE4eVE1Ym9CDQpZMVJQUzY0a2hkOFRnMjBTbXE3TldCUXNDYW9DTG1hOWNLNVJucEl4RzNNMmplMXdWVkhiSklQL3Nkd09STGJvDQo0TVhBT1h1b1NpYllUOGRYbjNaTFNYdFhMTU1LcElFamlCV3dSUXBIUGl3Vm12K0NVVXdKNE44V2dERDl4QjFGDQpWTEtlNmxPOHRFQ2s0SXRLRUsraG13VjNpeFVxb1NMa0dHMHJEUWVzWCtZalE3dU9wdDNIcXcwRCtKa29hTUptDQpycXV6VjlSTmVSWDF4Y2tVOUFVWHh5QVhpZE81TVhSSmM1dlZORVRadXhDaVF0RGtpT0ZNQkpxR1dFbHI2SC8zDQorOGlFWVBHbzI3ZzhKTmorTlhTV3hjNVk4V1NuMHhlYi9oVm8yVFIwKzdocWFKRzBBNlZDc0ZpeUcvRTVlNmdDDQorUVlTNXdtYkZjNkVzRmxMakFvRzFkT3V5bnBUV1VWMEJYK0VCRThoWm95dEVSVmRIU2pRamFLZnFpT0pLMzdQDQpvM04rRFlybjVNc0p4TlpxdTVxNEVINXc1eUNZM0ZGL1dRaUcvam1kSmo2ZTZ3PT0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0NCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQ0KTUlJRzVUQ0NCTTJnQXdJQkFnSVJBTnBEdlJPYjBsaTdUZFljck1UejIrQXdEUVlKS29aSWh2Y05BUUVNQlFBdw0KZ1lneEN6QUpCZ05WQkFZVEFsVlRNUk13RVFZRFZRUUlFd3BPWlhjZ1NtVnljMlY1TVJRd0VnWURWUVFIRXd0Sw0KWlhKelpYa2dRMmwwZVRFZU1Cd0dBMVVFQ2hNVlZHaGxJRlZUUlZKVVVsVlRWQ0JPWlhSM2IzSnJNUzR3TEFZRA0KVlFRREV5VlZVMFZTVkhKMWMzUWdVbE5CSUVObGNuUnBabWxqWVhScGIyNGdRWFYwYUc5eWFYUjVNQjRYRFRJdw0KTURJeE9EQXdNREF3TUZvWERUTXpNRFV3TVRJek5UazFPVm93UkRFTE1Ba0dBMVVFQmhNQ1Rrd3hHVEFYQmdOVg0KQkFvVEVFZEZRVTVVSUZabGNtVnVhV2RwYm1jeEdqQVlCZ05WQkFNVEVVZEZRVTVVSUU5V0lGSlRRU0JEUVNBMA0KTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUFwWWhpMWFFaVBzZzlaS1JNQXc5UQ0KcjhNdGhzcjZSMjBWU2ZGZWg3VGd3dExRaTZSU1JMT2g0b3I0RU1HLzF0aDhsaWp2N3huQk1WWmtUeXNGaVBtVA0KUGlMT2Z2eitRd08xTndqdmdZK0pyczdmU29WQS9UUWtYemN4dTRUbDNXSGkrcUptS0xKVnUvSk91SHVkNm1PcA0KTFdrSWJoT0RTek94QU5KMjRJR1B4OWg0T1hEeXk2LzM0MmVFNlVQWEN0SjhBemV1bVRHNkRmdjVLVngyNGxDRg0KVEdVekhVQitqK2cwbFNLZy9TZjFPemdDYWpKVjllbm1aLzg0eWRoNDh3UHA2dmJXZjFIME8zUmQzTGhwTVNWbg0KVHFGVExLWlNiUWVMY3gvbDlET0taZkJDQzlnaFd4c2dUcVc5Z1E3djNUM2FJZlNhVkM5cm53VnhPMFZqbURkUA0KRk5iZG94bmgwell3ZjQ1blYxUVFncFJ3Wko5M3lXZWRocDRjaDFhNkFqd3FzK3d2NG1aem1CU2pvdnRWMG1Ldw0KZCtDUWJTVG9hbEVVUDRRZUpxNFVkejVXTm1OTUk0T1lQNmNncm5sSjUwYWEwRFpQbEpxcktRUEdMNjlLUVF6MQ0KMldneHZoQ3VWVTcweTZaV0FQb3BCYTF5a2JzdHRwTHhBRFpyZTVjSDU3M2xJdUxIZGp4N05qcFlJWFJ4MitRSg0KVVJuWDJxeDM3ZVpJeFlYejhnZ00rd1hINlJEYlUzVjJvNURQNjdoWFBIU0FiQStwMG9yakFvY3BrMm9zeEhLbw0KTlNFM0xDak54OFdWZHhuWHZ1UTI4dEtkYUs2OWtuZm0zYkI3eHBkZnNOTlRQSDlFbGNqc2NXWnhwZVo1SWlqOA0KbHlyQ0cxejB2U1d0U0JzZ1NuVXlHL3NDQXdFQUFhT0NBWXN3Z2dHSE1COEdBMVVkSXdRWU1CYUFGRk41djFxcQ0KSzByUFZJRGgySnZBbmZLeUEyYkxNQjBHQTFVZERnUVdCQlJ2SFRWSkVHd3krbG1nbnJ5SzZCK1Z2bkY2RERBTw0KQmdOVkhROEJBZjhFQkFNQ0FZWXdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBREFkQmdOVkhTVUVGakFVQmdncg0KQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3T0FZRFZSMGdCREV3THpBdEJnUlZIU0FBTUNVd0l3WUlLd1lCQlFVSA0KQWdFV0YyaDBkSEJ6T2k4dmMyVmpkR2xuYnk1amIyMHZRMUJUTUZBR0ExVWRId1JKTUVjd1JhQkRvRUdHUDJoMA0KZEhBNkx5OWpjbXd1ZFhObGNuUnlkWE4wTG1OdmJTOVZVMFZTVkhKMWMzUlNVMEZEWlhKMGFXWnBZMkYwYVc5dQ0KUVhWMGFHOXlhWFI1TG1OeWJEQjJCZ2dyQmdFRkJRY0JBUVJxTUdnd1B3WUlLd1lCQlFVSE1BS0dNMmgwZEhBNg0KTHk5amNuUXVkWE5sY25SeWRYTjBMbU52YlM5VlUwVlNWSEoxYzNSU1UwRkJaR1JVY25WemRFTkJMbU55ZERBbA0KQmdnckJnRUZCUWN3QVlZWmFIUjBjRG92TDI5amMzQXVkWE5sY25SeWRYTjBMbU52YlRBTkJna3Foa2lHOXcwQg0KQVF3RkFBT0NBZ0VBVXRsQzNlMHhqLzFCTWZQaGRRaFVYZUxqYjB4cDhVRTI4a3pXRTV4RHpHS2JmR2duclQyUg0KbHc1Z0xJeCsvY05WcmFkLy8rTXJwVHBwTWx4cTU5QXNYWVpXM3hSYXNydmtqR2ZOUjN2dC8xUkFsOGlJMzFsRw0KaElnNmRmSVg1TjRlc0xrclFlTjhIaXlIS0g2a2htNDk2NklrVlZ0bnh6NUNnVVBxRVluNGVRKzRlZUVTcldCaA0KQXFYYWl2N0hSdnBzZHdMWWVrQWhucmxHcGlvWi9DSklUMlBUVHhmK0dITTZjdVVuTnFkVXpmdnJRZ0E4a3QxLw0KQVNYeDJvZC9NK2M4bmxKcXJHejI5bHJKdmVKT1NFTVgwYy90czAyV2hzZk1oa1lhNlh1alVaTG12UjFFcTA4cg0KNDgvRVo0bCt0NUw0d3QwRFY4VmFQYnNFQkYxRU9GcHovWVMySDZtU3djRmFOSmJuWXFxSkhJdm0zUExKSGtGbQ0KRW9MWFJWclFYZENUKzN3Z0JmZ1U2aGVDVjVDWUJ6L1lrcmRXRVM3dGlpVDhzVlVEcVhtVmxUc2JpUk5peUxzMg0KYm1FV1dGVWw3NmpWaUlKb2c1Zm9uZ0VxTjNqTElHVEcvbVhySlQxVXl5bUljb2JuSUdyYnd3UlZ6L21wRlFvMA0KdkJZSWkxazJUaFZoMER4ODhCYkY5WWlQODRkZDhGa241d2JFNkZ4WFlKMjg3cWZSVGdtaGVQZWNQYzczWXJ6dA0KYXBkUmNzS1ZHa09wYVRJSlAvbCtsQUhSTFp4ay9kVXR5Tjk1RysrYk9TUXFuT0NwVlBhYlVHbDJFL09FeUZycA0KSXB3Z3UyTC9XSmNsdmQ2ZytaQS9pV2tMU01jcG5GYit1WDZRQnF2RDYrUk54dWwxRmFCNWlIWT0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0NCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQ0KTUlJRjNqQ0NBOGFnQXdJQkFnSVFBZjF0TVB5anlsR29HN3hrRGpVRExUQU5CZ2txaGtpRzl3MEJBUXdGQURDQg0KaURFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBZ1RDazVsZHlCS1pYSnpaWGt4RkRBU0JnTlZCQWNUQzBwbA0KY25ObGVTQkRhWFI1TVI0d0hBWURWUVFLRXhWVWFHVWdWVk5GVWxSU1ZWTlVJRTVsZEhkdmNtc3hMakFzQmdOVg0KQkFNVEpWVlRSVkpVY25WemRDQlNVMEVnUTJWeWRHbG1hV05oZEdsdmJpQkJkWFJvYjNKcGRIa3dIaGNOTVRBdw0KTWpBeE1EQXdNREF3V2hjTk16Z3dNVEU0TWpNMU9UVTVXakNCaURFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVg0KQkFnVENrNWxkeUJLWlhKelpYa3hGREFTQmdOVkJBY1RDMHBsY25ObGVTQkRhWFI1TVI0d0hBWURWUVFLRXhWVQ0KYUdVZ1ZWTkZVbFJTVlZOVUlFNWxkSGR2Y21zeExqQXNCZ05WQkFNVEpWVlRSVkpVY25WemRDQlNVMEVnUTJWeQ0KZEdsbWFXTmhkR2x2YmlCQmRYUm9iM0pwZEhrd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJSw0KQW9JQ0FRQ0FFbVVYTmc3RDJ3aXowS3hYRFhidHpTZlRUSzFRZzJIaXFpQk5DUzFrQ2R6T2laL01QYW5zOXMvQg0KM1BIVHNkWjdOeWdSSzBmYU9jYThPaG0wWDZhOWZaMmpZMEsyZHZLcE95dVIrT0p2ME93V0lKQUpQdUxvZE1rWQ0KdEpIVVltVGJmNk1HOFlnWWFwQWlQTHorRS9DSEZIdjI1QitPMU9SUnhoRm5SZ2hSeTRZVVZEKzhNLzUrYkp6Lw0KRnAwWXZWR09OYWFuWnNoeVo5c2hackhVbTNnRHdGQTY2TXp3M0x5ZVRQNnZCWlkxSDFkYXQvL08rVDIzTExiMg0KVk4zSTV4STZUYTVNaXJkY21yUzNJRDNLZnlJMHJuNDdhR1lCUk9jQlRrWlRtek5nOTVTK1V6ZVFjMFB6TXNOVA0KNzl1cS9uUk9hY2RyakdDVDNzVEhETi9oTXE3TWt6dFJlSlZuaSs0OVZ2NE0wR2tQR3cvekpTWnJNMjMzYmtmNg0KYzBQbGZnNmxackVwZkRLRVkxV0p4QTNCazFRd0dST3MwMzAzcCt0ZE9tdzFYTnRCMXhMYXFVa0wzOWlBaWdtVA0KWW82MVpzOGxpTTJFdUxFL3BEa1AyUUtlNnhKTWxYenphd1dwWGhhRHpMaG40dWdUbmN4Ymd0Tk1zKzFiLzk3bA0KYzZ3ak95MEF2elZWZEFsSjJFbFlHbitTTnVaUmtnN3pKbjBjVFJlOHlleERKdEMvUVY5QXFVUkU5Sm5uVjRlZQ0KVUI5WFZLZysvWFJqTDdGUVpRbm1XRUl1UXhwTXRQQWxSMW42QkI2VDFDWkdTbENCc3Q2K2VMZjhaeFhoeVZlRQ0KSGc5ajF1bGl1dFpmVlM3cVhNWW9DQVFsT2JnT0s2bnlUSmNjQno4TlV2WHQ3eStDRHdJREFRQUJvMEl3UURBZA0KQmdOVkhRNEVGZ1FVVTNtL1dxb3JTczlVZ09IWW04Q2Q4cklEWnNzd0RnWURWUjBQQVFIL0JBUURBZ0VHTUE4Rw0KQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVNQlFBRGdnSUJBRnpVZkEzUDl3RjlRWmxsREhQRg0KVXAvTCtNK1pCbjhiMmtNVm41NENWVmVXRlBGU1BDZUhsQ2p0SHpvQk42SjIvRk5Rd0lTYnhtdE91b3doVDZLTw0KVldLUjgya1YyTHlJNDhTcUMvM3ZxT2xMVlNvR0lHMVZlQ2taN2w4d1hFc2tFVlgvSkpwdVhpb3I3Z3RObjMvMw0KQVRpVUZKVkRCd243WUtudUhLc1NqS0NhWHFlWWFsbHRpejhJKzhqUlJhOFlGV1NRRWc5ektDN0Y0aVJPL0Zqcw0KOFBSRi9pS3o2eStPMHRsRllRWEJsMitvZG5LUGk0dzJyNzhOQmM1eGplYW1ieDlzcG5GaXhkalFnM0lNOFdjUg0KaVF5Y0UweHlOTis4MVhIZnFuSGQ0YmxzakR3U1hXWGF2VmNTdGtOci8rWGVUV1lSVWMrWnJ1d1h0dWh4a1l6ZQ0KU2Y3ZE5YR2lGU2VVSE05aDR5YTdiNk5uSlNGZDV0MGRDeTVvR3p1Q3IreURaNFhVbUZGMHNibVpnSW4vZjNnWg0KWEhsS1lDNlNRSzVNTnlvc3ljZGl5QTVkOXpaYnl1QWxKUUcwM1JvSG5IY0FQOURjMWV3OTFQcTdQOHlGMW05Lw0KcVMzZnVRTDM5WmVhdFRYYXcyZXdoMHFwS0o0amp2OWNKMnZoc0UvekIrNEFMdFJaaDh0U1FaWHE5RWZYN21SQg0KVlh5TldRS1YzV0tkd3JudVdpaDBoS1didDVESERBZmY5WWsyZERMV0tNR3dzQXZnbkV6REhOYjg0Mm0xUjBhQg0KTDZLQ3E5TmpSSERFamY4dE03cXRqM3UxY0lpdVBoblBRQ2pZL01pUXUxMlpJdlZTNWxqRkg0Z3hRKzZJSGRmRw0Kamp4RGFoMm5HTjU5UFJieFl2bktrS2o5DQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tDQo=
  clouds.yaml: REDACTED
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: bsc-gaia-cloud-config
  namespace: default
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: bsc-gaia-md-0
  namespace: default
spec:
  template:
    spec:
      files: []
      preKubeadmCommands: [
	"apt-get update;", "apt-get install nfs-common -y;", 
	"mkdir -p /mnt/nfs/shared", 
	"echo 192.168.0.15:/mnt/nfs/shared    /mnt/nfs/shared    nfs    defaults    0 0 >> /etc/fstab"]
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: openstack:///'{{ instance_id }}'
          name: '{{ local_hostname }}'
      postKubeadmCommands: ["sudo mount -a"]
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: bsc-gaia
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: bsc-gaia-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: OpenStackCluster
    name: bsc-gaia
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: bsc-gaia-md-0
  namespace: default
spec:
  clusterName: bsc-gaia
  replicas: 3
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: bsc-gaia-md-0
      clusterName: bsc-gaia
      failureDomain: nova
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        name: bsc-gaia-md-0
      version: 1.30.2
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: bsc-gaia-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    files: []
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackMachineTemplate
      name: bsc-gaia-control-plane
  replicas: 1
  version: 1.30.2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: bsc-gaia
  namespace: default
spec:
  apiServerLoadBalancer:
    enabled: false
  externalNetwork:
    id: fbba2c3c-7fdf-4bdc-8a02-6d852446c79a
  identityRef:
    cloudName: bsc
    name: bsc-gaia-cloud-config
  managedSecurityGroups:
    allNodesSecurityGroupRules:
    - description: Created by cluster-api-provider-openstack - BGP (calico)
      direction: ingress
      etherType: IPv4
      name: BGP (Calico)
      portRangeMax: 179
      portRangeMin: 179
      protocol: tcp
      remoteManagedGroups:
      - controlplane
      - worker
    - description: Created by cluster-api-provider-openstack - IP-in-IP (calico)
      direction: ingress
      etherType: IPv4
      name: IP-in-IP (calico)
      protocol: "4"
      remoteManagedGroups:
      - controlplane
      - worker
  managedSubnets:
  - cidr: 10.6.0.0/24
    dnsNameservers:
    - 84.88.52.35
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: bsc-gaia-control-plane
  namespace: default
spec:
  template:
    spec:
      ports:
        - network:
            filter:
               name: k8s-clusterapi-cluster-default-bsc-gaia
        - network:
            filter:
               name: net-BSC24Spacious
      flavor: bsc.mem.m
      image:
        filter:
          name: Ubuntu-kube-1.30.2
      sshKeyName: malcolm_bsc_capi_test
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: bsc-gaia-md-0
  namespace: default
spec:
  template:
    spec:
      ports:
        - network:
            filter:
               name: k8s-clusterapi-cluster-default-bsc-gaia
        - network:
            filter:
               name: net-BSC24Spacious
      flavor: bsc.mem.2xl
      image:
        filter:
          name: Ubuntu-kube-1.30.2
      sshKeyName: malcolm_bsc_capi_test
