apiVersion: v1
data:
  cacert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlIbERDQ0JYeWdBd0lCQWdJUkFPaGpXSlpNaFNpakpMNFBZb0FmMGdNd0RRWUpLb1pJaHZjTkFRRU1CUUF3DQpSREVMTUFrR0ExVUVCaE1DVGt3eEdUQVhCZ05WQkFvVEVFZEZRVTVVSUZabGNtVnVhV2RwYm1jeEdqQVlCZ05WDQpCQU1URVVkRlFVNVVJRTlXSUZKVFFTQkRRU0EwTUI0WERUSTBNRGt4TkRBd01EQXdNRm9YRFRJMU1UQXhNekl6DQpOVGsxT1Zvd2NERUxNQWtHQTFVRUJoTUNSMEl4RnpBVkJnTlZCQWdURGtOaGJXSnlhV1JuWlhOb2FYSmxNU0F3DQpIZ1lEVlFRS0V4ZFZibWwyWlhKemFYUjVJRzltSUVOaGJXSnlhV1JuWlRFbU1DUUdBMVVFQXhNZFlYSmpkWE11DQpiM0JsYm5OMFlXTnJMbWh3WXk1allXMHVZV011ZFdzd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3DQpnZ0VLQW9JQkFRRE40NkJVYlFLNkw1RHhCeWFQVFpraEh1SE9ZOFBnK0ZNYWpKcXBvaVViQWhzWGdaUkFwcW1wDQpFelF0aklmbTY3UFhQNEFoWWZEbHd0YWt3M2JuME41V3JXODlQZUp6VzgwU3hxRXQySmQ5NGlxNmJxc1lBMFBCDQpESnZrakFWTjlaODVyN0pFZlBmYkdFMWxiVnVlUFkxSG04QzBJSlBpanZLblU4NXBVUVVRN01NUm9oT3o4bEFYDQp3U3I1T1pIQVFtUGtoV3QzcktWUVFrZXRrWTVZZEJSNU9NeU9DMmFRQWhXZkFSSDFpcDFoVk1uTUg0WWZESnRCDQpBcVV3ZHFKMmhzd3JRZXlWa2RCTUJoR3Y4UWs0N0dUcFRLM2k5ZzZWOEI3aTFaOGFaSFJEcmt3QzQ1Z3RjVTFLDQpTSFpKQVhMYmxmWDJPRkpJOUZiRFhRVGc1MEtQRTRKRkFnTUJBQUdqZ2dOVE1JSURUekFmQmdOVkhTTUVHREFXDQpnQlJ2SFRWSkVHd3krbG1nbnJ5SzZCK1Z2bkY2RERBZEJnTlZIUTRFRmdRVThNT2Y5b281T3VqcHROMVMrT25HDQpFcmE3Yk93d0RnWURWUjBQQVFIL0JBUURBZ1dnTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwbEJCWXdGQVlJDQpLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNRWtHQTFVZElBUkNNRUF3TkFZTEt3WUJCQUd5TVFFQ0FrOHdKVEFqDQpCZ2dyQmdFRkJRY0NBUllYYUhSMGNITTZMeTl6WldOMGFXZHZMbU52YlM5RFVGTXdDQVlHWjRFTUFRSUNNRDhHDQpBMVVkSHdRNE1EWXdOS0F5b0RDR0xtaDBkSEE2THk5SFJVRk9WQzVqY213dWMyVmpkR2xuYnk1amIyMHZSMFZCDQpUbFJQVmxKVFFVTkJOQzVqY213d2RRWUlLd1lCQlFVSEFRRUVhVEJuTURvR0NDc0dBUVVGQnpBQ2hpNW9kSFJ3DQpPaTh2UjBWQlRsUXVZM0owTG5ObFkzUnBaMjh1WTI5dEwwZEZRVTVVVDFaU1UwRkRRVFF1WTNKME1Da0dDQ3NHDQpBUVVGQnpBQmhoMW9kSFJ3T2k4dlIwVkJUbFF1YjJOemNDNXpaV04wYVdkdkxtTnZiVEJMQmdOVkhSRUVSREJDDQpnaDFoY21OMWN5NXZjR1Z1YzNSaFkyc3VhSEJqTG1OaGJTNWhZeTUxYTRJaGQzZDNMbUZ5WTNWekxtOXdaVzV6DQpkR0ZqYXk1b2NHTXVZMkZ0TG1GakxuVnJNSUlCZmdZS0t3WUJCQUhXZVFJRUFnU0NBVzRFZ2dGcUFXZ0FkZ0RkDQozTW8wbGRmaEZnWG5sVEw2eDUvNFBSeFEzOXNBT2hRU2Rnb3NyTHZJS2dBQUFaSHhtSjVkQUFBRUF3QkhNRVVDDQpJUUNOcnZJY2JCem1EcjM3WHVPNW5CeTE4Zmh1d1RnaUNtSm9mbnFNT1prOTNRSWdaeHVyOFZmT0YxeDlmN25UDQp6Y3l5T1V2ZUxJUDFGdENWcW1PcVA2cDBrUlVBZGdBTjRmSXdLOU1Od1VCaUVnbnFWUzc4UjNSOHNkZnBNTzhPDQpRaDYwZms2cU5BQUFBWkh4bUozMEFBQUVBd0JITUVVQ0lBcDY4eEJ2RjhWcUowNyt6cjdtNkQ0U2RSaDlkTUY4DQozaForSjNnMEFraUFBaUVBNEUrUURadmdVYVFBS2ljeFpnaSsxNW9mSXBCa3puN1dtRXYyWTQzd2p3c0FkZ0FTDQo4VTQwdlZOeVRJUUdHY09QUDNvVCtPZTFZb2VJbkcwd0JZVHI1WVltT2dBQUFaSHhtSjN5QUFBRUF3QkhNRVVDDQpJUUM1Wkt1bTBvNUcyVTE5RjZnUkZvMDR6cHZhbm5xK0dnTkFxTzhmUEVER0FnSWdPbEw1bzgzK01HOC9aRDFjDQpBajQxa2JnU0tqUU5vSFVZeXEvK2hJN0dBcFl3RFFZSktvWklodmNOQVFFTUJRQURnZ0lCQUNnRnVxWHdMVVZSDQpaMDF6QnhwZ2kzRWRUUTJWMmkvSU44UHhSb1BhbEdJSm5HNVJOV1l4eDN4UzZVQUtIbmI3ZURYWVRPQnZmcmF3DQoxN0NvVWdKNjA0bVg4cDJub0Q4Y1QxMHVOQTlsbEFDanNIY2pQMzFVNUpHRC82b3J6UlVxYll3dUlwQ2V1Sm9yDQpPMTBOZFliajQxT2VBcVBzQlBGeDhhM2RsallSRFNqeUhVelpnS0pTcCtZV1FmRnFCODgxeGZ4WWM5d2I1aHh3DQpkVWhTc2lhNDhNemdabXdCeEUrZEdzRXkzK05tMThjVlNyL1lvcVRURndPMlJ4cXZJb1BzYXlqZW5rYkJ5ZTlqDQo2M3lPZnpCTUlUOEkxaHZGNHBpcDBTbWZjWVhiOHJFOTQyaUVHZHp6RnVMOTJ5aTBOanRCRDNleVdseHllZHpxDQpsZmVLZ0x3VGsvZnFtNFl2d3U2YmlLSmF4VFUxcjhwbnhqYzNYSDlTYWVwQmViRHIwazRvYzZwUUV4QitBMEo0DQp3Q0NvVVVJQjlDbHJyWDZhc1RMWUxoSDIyb3UrdEhXMzdsYkF0VEZwTG8vMXl0azBRZ3gvbTFsVU9uRTIvL2ZvDQpLWXl1djd1aHoxNDZ4NG5ST1R5bEFuNGpZeWtnYzBnb1NKVnVJblFIWmtXdFM5RzdoWkErVjdjNkUzWUtZeDlKDQo3cDFQbkpqbkJaOWxZUE9OVExOdlorb1llc2lKeGFuLzJBRWQ2QUs3RW9JcytFNkhCZUJkZStDTm9TampIcFQzDQpwOHJuM2EyUEorWU1aTGIyVDFrTGV5VkFqNWtSdUE2b291T2w5ZWdka3ErVGYvODl2SGQwMzVZZ293dW9FS3hHDQphL0xqdCt0OEVlUGZxN0RPaXFVZEdTSXcrVHdMRHFtZw0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlHNVRDQ0JNMmdBd0lCQWdJUkFOcER2Uk9iMGxpN1RkWWNyTVR6MitBd0RRWUpLb1pJaHZjTkFRRU1CUUF3DQpnWWd4Q3pBSkJnTlZCQVlUQWxWVE1STXdFUVlEVlFRSUV3cE9aWGNnU21WeWMyVjVNUlF3RWdZRFZRUUhFd3RLDQpaWEp6WlhrZ1EybDBlVEVlTUJ3R0ExVUVDaE1WVkdobElGVlRSVkpVVWxWVFZDQk9aWFIzYjNKck1TNHdMQVlEDQpWUVFERXlWVlUwVlNWSEoxYzNRZ1VsTkJJRU5sY25ScFptbGpZWFJwYjI0Z1FYVjBhRzl5YVhSNU1CNFhEVEl3DQpNREl4T0RBd01EQXdNRm9YRFRNek1EVXdNVEl6TlRrMU9Wb3dSREVMTUFrR0ExVUVCaE1DVGt3eEdUQVhCZ05WDQpCQW9URUVkRlFVNVVJRlpsY21WdWFXZHBibWN4R2pBWUJnTlZCQU1URVVkRlFVNVVJRTlXSUZKVFFTQkRRU0EwDQpNSUlDSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQXBZaGkxYUVpUHNnOVpLUk1BdzlRDQpyOE10aHNyNlIyMFZTZkZlaDdUZ3d0TFFpNlJTUkxPaDRvcjRFTUcvMXRoOGxpanY3eG5CTVZaa1R5c0ZpUG1UDQpQaUxPZnZ6K1F3TzFOd2p2Z1krSnJzN2ZTb1ZBL1RRa1h6Y3h1NFRsM1dIaStxSm1LTEpWdS9KT3VIdWQ2bU9wDQpMV2tJYmhPRFN6T3hBTkoyNElHUHg5aDRPWER5eTYvMzQyZUU2VVBYQ3RKOEF6ZXVtVEc2RGZ2NUtWeDI0bENGDQpUR1V6SFVCK2orZzBsU0tnL1NmMU96Z0NhakpWOWVubVovODR5ZGg0OHdQcDZ2YldmMUgwTzNSZDNMaHBNU1ZuDQpUcUZUTEtaU2JRZUxjeC9sOURPS1pmQkNDOWdoV3hzZ1RxVzlnUTd2M1QzYUlmU2FWQzlybndWeE8wVmptRGRQDQpGTmJkb3huaDB6WXdmNDVuVjFRUWdwUndaSjkzeVdlZGhwNGNoMWE2QWp3cXMrd3Y0bVp6bUJTam92dFYwbUt3DQpkK0NRYlNUb2FsRVVQNFFlSnE0VWR6NVdObU5NSTRPWVA2Y2dybmxKNTBhYTBEWlBsSnFyS1FQR0w2OUtRUXoxDQoyV2d4dmhDdVZVNzB5NlpXQVBvcEJhMXlrYnN0dHBMeEFEWnJlNWNINTczbEl1TEhkang3TmpwWUlYUngyK1FKDQpVUm5YMnF4MzdlWkl4WVh6OGdnTSt3WEg2UkRiVTNWMm81RFA2N2hYUEhTQWJBK3Awb3JqQW9jcGsyb3N4SEtvDQpOU0UzTENqTng4V1ZkeG5YdnVRMjh0S2RhSzY5a25mbTNiQjd4cGRmc05OVFBIOUVsY2pzY1daeHBlWjVJaWo4DQpseXJDRzF6MHZTV3RTQnNnU25VeUcvc0NBd0VBQWFPQ0FZc3dnZ0dITUI4R0ExVWRJd1FZTUJhQUZGTjV2MXFxDQpLMHJQVklEaDJKdkFuZkt5QTJiTE1CMEdBMVVkRGdRV0JCUnZIVFZKRUd3eStsbWducnlLNkIrVnZuRjZEREFPDQpCZ05WSFE4QkFmOEVCQU1DQVlZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFEQWRCZ05WSFNVRUZqQVVCZ2dyDQpCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdPQVlEVlIwZ0JERXdMekF0QmdSVkhTQUFNQ1V3SXdZSUt3WUJCUVVIDQpBZ0VXRjJoMGRIQnpPaTh2YzJWamRHbG5ieTVqYjIwdlExQlRNRkFHQTFVZEh3UkpNRWN3UmFCRG9FR0dQMmgwDQpkSEE2THk5amNtd3VkWE5sY25SeWRYTjBMbU52YlM5VlUwVlNWSEoxYzNSU1UwRkRaWEowYVdacFkyRjBhVzl1DQpRWFYwYUc5eWFYUjVMbU55YkRCMkJnZ3JCZ0VGQlFjQkFRUnFNR2d3UHdZSUt3WUJCUVVITUFLR00yaDBkSEE2DQpMeTlqY25RdWRYTmxjblJ5ZFhOMExtTnZiUzlWVTBWU1ZISjFjM1JTVTBGQlpHUlVjblZ6ZEVOQkxtTnlkREFsDQpCZ2dyQmdFRkJRY3dBWVlaYUhSMGNEb3ZMMjlqYzNBdWRYTmxjblJ5ZFhOMExtTnZiVEFOQmdrcWhraUc5dzBCDQpBUXdGQUFPQ0FnRUFVdGxDM2UweGovMUJNZlBoZFFoVVhlTGpiMHhwOFVFMjhreldFNXhEekdLYmZHZ25yVDJSDQpsdzVnTEl4Ky9jTlZyYWQvLytNcnBUcHBNbHhxNTlBc1hZWlczeFJhc3J2a2pHZk5SM3Z0LzFSQWw4aUkzMWxHDQpoSWc2ZGZJWDVONGVzTGtyUWVOOEhpeUhLSDZraG00OTY2SWtWVnRueHo1Q2dVUHFFWW40ZVErNGVlRVNyV0JoDQpBcVhhaXY3SFJ2cHNkd0xZZWtBaG5ybEdwaW9aL0NKSVQyUFRUeGYrR0hNNmN1VW5OcWRVemZ2clFnQThrdDEvDQpBU1h4Mm9kL00rYzhubEpxckd6Mjlsckp2ZUpPU0VNWDBjL3RzMDJXaHNmTWhrWWE2WHVqVVpMbXZSMUVxMDhyDQo0OC9FWjRsK3Q1TDR3dDBEVjhWYVBic0VCRjFFT0Zwei9ZUzJINm1Td2NGYU5KYm5ZcXFKSEl2bTNQTEpIa0ZtDQpFb0xYUlZyUVhkQ1QrM3dnQmZnVTZoZUNWNUNZQnovWWtyZFdFUzd0aWlUOHNWVURxWG1WbFRzYmlSTml5THMyDQpibUVXV0ZVbDc2alZpSUpvZzVmb25nRXFOM2pMSUdURy9tWHJKVDFVeXltSWNvYm5JR3Jid3dSVnovbXBGUW8wDQp2QllJaTFrMlRoVmgwRHg4OEJiRjlZaVA4NGRkOEZrbjV3YkU2RnhYWUoyODdxZlJUZ21oZVBlY1BjNzNZcnp0DQphcGRSY3NLVkdrT3BhVElKUC9sK2xBSFJMWnhrL2RVdHlOOTVHKytiT1NRcW5PQ3BWUGFiVUdsMkUvT0V5RnJwDQpJcHdndTJML1dKY2x2ZDZnK1pBL2lXa0xTTWNwbkZiK3VYNlFCcXZENitSTnh1bDFGYUI1aUhZPQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlGM2pDQ0E4YWdBd0lCQWdJUUFmMXRNUHlqeWxHb0c3eGtEalVETFRBTkJna3Foa2lHOXcwQkFRd0ZBRENCDQppREVMTUFrR0ExVUVCaE1DVlZNeEV6QVJCZ05WQkFnVENrNWxkeUJLWlhKelpYa3hGREFTQmdOVkJBY1RDMHBsDQpjbk5sZVNCRGFYUjVNUjR3SEFZRFZRUUtFeFZVYUdVZ1ZWTkZVbFJTVlZOVUlFNWxkSGR2Y21zeExqQXNCZ05WDQpCQU1USlZWVFJWSlVjblZ6ZENCU1UwRWdRMlZ5ZEdsbWFXTmhkR2x2YmlCQmRYUm9iM0pwZEhrd0hoY05NVEF3DQpNakF4TURBd01EQXdXaGNOTXpnd01URTRNak0xT1RVNVdqQ0JpREVMTUFrR0ExVUVCaE1DVlZNeEV6QVJCZ05WDQpCQWdUQ2s1bGR5QktaWEp6WlhreEZEQVNCZ05WQkFjVEMwcGxjbk5sZVNCRGFYUjVNUjR3SEFZRFZRUUtFeFZVDQphR1VnVlZORlVsUlNWVk5VSUU1bGRIZHZjbXN4TGpBc0JnTlZCQU1USlZWVFJWSlVjblZ6ZENCU1UwRWdRMlZ5DQpkR2xtYVdOaGRHbHZiaUJCZFhSb2IzSnBkSGt3Z2dJaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQ0R3QXdnZ0lLDQpBb0lDQVFDQUVtVVhOZzdEMndpejBLeFhEWGJ0elNmVFRLMVFnMkhpcWlCTkNTMWtDZHpPaVovTVBhbnM5cy9CDQozUEhUc2RaN055Z1JLMGZhT2NhOE9obTBYNmE5ZloyalkwSzJkdktwT3l1UitPSnYwT3dXSUpBSlB1TG9kTWtZDQp0SkhVWW1UYmY2TUc4WWdZYXBBaVBMeitFL0NIRkh2MjVCK08xT1JSeGhGblJnaFJ5NFlVVkQrOE0vNStiSnovDQpGcDBZdlZHT05hYW5ac2h5WjlzaFpySFVtM2dEd0ZBNjZNenczTHllVFA2dkJaWTFIMWRhdC8vTytUMjNMTGIyDQpWTjNJNXhJNlRhNU1pcmRjbXJTM0lEM0tmeUkwcm40N2FHWUJST2NCVGtaVG16Tmc5NVMrVXplUWMwUHpNc05UDQo3OXVxL25ST2FjZHJqR0NUM3NUSEROL2hNcTdNa3p0UmVKVm5pKzQ5VnY0TTBHa1BHdy96SlNack0yMzNia2Y2DQpjMFBsZmc2bFpyRXBmREtFWTFXSnhBM0JrMVF3R1JPczAzMDNwK3RkT213MVhOdEIxeExhcVVrTDM5aUFpZ21UDQpZbzYxWnM4bGlNMkV1TEUvcERrUDJRS2U2eEpNbFh6emF3V3BYaGFEekxobjR1Z1RuY3hiZ3ROTXMrMWIvOTdsDQpjNndqT3kwQXZ6VlZkQWxKMkVsWUduK1NOdVpSa2c3ekpuMGNUUmU4eWV4REp0Qy9RVjlBcVVSRTlKbm5WNGVlDQpVQjlYVktnKy9YUmpMN0ZRWlFubVdFSXVReHBNdFBBbFIxbjZCQjZUMUNaR1NsQ0JzdDYrZUxmOFp4WGh5VmVFDQpIZzlqMXVsaXV0WmZWUzdxWE1Zb0NBUWxPYmdPSzZueVRKY2NCejhOVXZYdDd5K0NEd0lEQVFBQm8wSXdRREFkDQpCZ05WSFE0RUZnUVVVM20vV3FvclNzOVVnT0hZbThDZDhySURac3N3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHDQpBMVVkRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRU1CUUFEZ2dJQkFGelVmQTNQOXdGOVFabGxESFBGDQpVcC9MK00rWkJuOGIya01WbjU0Q1ZWZVdGUEZTUENlSGxDanRIem9CTjZKMi9GTlF3SVNieG10T3Vvd2hUNktPDQpWV0tSODJrVjJMeUk0OFNxQy8zdnFPbExWU29HSUcxVmVDa1o3bDh3WEVza0VWWC9KSnB1WGlvcjdndE5uMy8zDQpBVGlVRkpWREJ3bjdZS251SEtzU2pLQ2FYcWVZYWxsdGl6OEkrOGpSUmE4WUZXU1FFZzl6S0M3RjRpUk8vRmpzDQo4UFJGL2lLejZ5K08wdGxGWVFYQmwyK29kbktQaTR3MnI3OE5CYzV4amVhbWJ4OXNwbkZpeGRqUWczSU04V2NSDQppUXljRTB4eU5OKzgxWEhmcW5IZDRibHNqRHdTWFdYYXZWY1N0a05yLytYZVRXWVJVYytacnV3WHR1aHhrWXplDQpTZjdkTlhHaUZTZVVITTloNHlhN2I2Tm5KU0ZkNXQwZEN5NW9HenVDcit5RFo0WFVtRkYwc2JtWmdJbi9mM2daDQpYSGxLWUM2U1FLNU1OeW9zeWNkaXlBNWQ5elpieXVBbEpRRzAzUm9IbkhjQVA5RGMxZXc5MVBxN1A4eUYxbTkvDQpxUzNmdVFMMzlaZWF0VFhhdzJld2gwcXBLSjRqanY5Y0oydmhzRS96Qis0QUx0UlpoOHRTUVpYcTlFZlg3bVJCDQpWWHlOV1FLVjNXS2R3cm51V2loMGhLV2J0NURIREFmZjlZazJkRExXS01Hd3NBdmduRXpESE5iODQybTFSMGFCDQpMNktDcTlOalJIREVqZjh0TTdxdGozdTFjSWl1UGhuUFFDalkvTWlRdTEyWkl2VlM1bGpGSDRneFErNklIZGZHDQpqanhEYWgybkdONTlQUmJ4WXZuS2tLajkNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0NCg==
  clouds.yaml: REDACTED
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: iris-gaia-green-cloud-config
  namespace: default
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: iris-gaia-green-md-0
  namespace: default
spec:
  template:
    spec:
      preKubeadmCommands: ["apt-get update;apt-get install ceph-common -y; mkdir -p /mnt/kubernetes_scratch_share",
        "mkdir /mnt/edr3",
        "mkdir /mnt/dr3_data_share",
        "echo 10.4.200.9:6789,10.4.200.13:6789,10.4.200.17:6789,10.4.200.25:6789,10.4.200.26:6789:/volumes/_nogroup/5e74d2f7-dba9-40aa-ab90-526c8d0d58e5     /mnt/edr3    ceph    name=aglais-data-gaia-edr3-2048-ro,noatime,_netdev    0       2 >> /etc/fstab",
        "echo 10.4.200.9:6789,10.4.200.13:6789,10.4.200.17:6789,10.4.200.25:6789,10.4.200.26:6789:/volumes/_nogroup/5875b16a-3fd1-489e-a342-d50548e4e522     /mnt/dr3_data_share    ceph    name=aglais-data-gaia-dr3-2048-new-ro,noatime,_netdev    0       2 >> /etc/fstab" 
       ]
      postKubeadmCommands: ["sudo mount -a"]
      files: 
      - path: /etc/ceph/ceph.conf
        content: |
              [global]
              fsid = a900cf30-f8a3-42bf-98d6-af7ce92f1a1a
              mon_host = [v2:10.4.200.13:3300/0,v1:10.4.200.13:6789/0] [v2:10.4.200.9:3300/0,v1:10.4.200.9:6789/0] [v2:10.4.200.17:3300/0,v1:10.4.200.17:6789/0] [v2:10.4.200.26:3300/0,v1:10.4.200.26:6789/0] [v2:10.4.200.25:3300/0,v1:10.4.200.25:6789/0]
      - path: /etc/ceph/ceph.client.aglais-data-gaia-edr3-2048-ro.keyring
        content: |
          [client.aglais-data-gaia-edr3-2048-ro]
            key = REDACTED
      - path: /etc/ceph/ceph.client.aglais-data-gaia-dr3-2048-new-ro.keyring
        content: |
          [client.aglais-data-gaia-dr3-2048-new-ro]
            key = REDACTED
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: openstack:///'{{ instance_id }}'
          name: '{{ local_hostname }}'
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: iris-gaia-green
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: iris-gaia-green-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: OpenStackCluster
    name: iris-gaia-green
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: iris-gaia-green-md-0
  namespace: default
spec:
  clusterName: iris-gaia-green
  replicas: 4
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: iris-gaia-green-md-0
      clusterName: iris-gaia-green
      failureDomain: nova
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        name: iris-gaia-green-md-0
      version: 1.30.2
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: iris-gaia-green-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    files: []
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackMachineTemplate
      name: iris-gaia-green-control-plane
  replicas: 3
  version: 1.30.2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: iris-gaia-green
  namespace: default
spec:
  apiServerLoadBalancer:
    enabled: true
  externalNetwork:
    id: 57add367-d205-4030-a929-d75617a7c63e
  identityRef:
    cloudName: iris-gaia-green
    name: iris-gaia-green-cloud-config
  managedSecurityGroups:
    allNodesSecurityGroupRules:
    - description: Created by cluster-api-provider-openstack - BGP (calico)
      direction: ingress
      etherType: IPv4
      name: BGP (Calico)
      portRangeMax: 179
      portRangeMin: 179
      protocol: tcp
      remoteManagedGroups:
      - controlplane
      - worker
    - description: Created by cluster-api-provider-openstack - IP-in-IP (calico)
      direction: ingress
      etherType: IPv4
      name: IP-in-IP (calico)
      protocol: "4"
      remoteManagedGroups:
      - controlplane
      - worker
  network:
    filter:
      name: kubernetes-cluster-network-with-ceph
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: iris-gaia-green-control-plane
  namespace: default
spec:
  template:
    spec:
      flavor: vm.icelake.opt.v1.small.1GB.local
      image:
        filter:
          name: Ubuntu-Noble-24.04-20250217-kube-1.30.2
      sshKeyName: iris-malcolm-kube-test-keypair
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: iris-gaia-green-md-0
  namespace: default
spec:
  template:
    spec:
      flavor: vm.saphrapids.himem.opt.v1.large.1GB.local
      image:
        filter:
          name: Ubuntu-Noble-24.04-20250217-kube-1.30.2
      sshKeyName: iris-malcolm-kube-test-keypair
