kind: KubeadmConfigTemplate
metadata:
  name: iris-gaia-red-ceph-md-0
  namespace: default
spec:
  template:
    spec:
      mounts: []
      preKubeadmCommands: ["apt-get update;", "apt-get install ceph-common -y;", "mkdir -p /mnt/kubernetes_scratch_share", "echo 10.4.200.9:6789,10.4.200.13:6789,10.4.200.17:6789,10.4.200.25:6789,10.4.200.26:6789:/volumes/_nogroup/280b44fc-d423-4496-8fb8-79bfc1f58b97/35e407e9-a34b-4c64-b480-3380002d64f8 /mnt/kubernetes_scratch_share ceph name=kubernetes-scratch-share,noatime,_netdev 0 2 >> /etc/fstab"]
      files:
      - path: /etc/ceph/ceph.conf
        content: |
              [global]
              fsid = a900cf30-f8a3-42bf-98d6-af7ce92f1a1a
              mon_host = [v2:10.4.200.13:3300/0,v1:10.4.200.13:6789/0] [v2:10.4.200.9:3300/0,v1:10.4.200.9:6789/0] [v2:10.4.200.17:3300/0,v1:10.4.200.17:6789/0] [v2:10.4.200.26:3300/0,v1:10.4.200.26:6789/0] [v2:10.4.200.25:3300/0,v1:10.4.200.25:6789/0]

      - path: /etc/ceph/ceph.client.kubernetes-scratch-share.keyring
        content: |
          [client.kubernetes-scratch-share]
          key = **REDACTED**

      postKubeadmCommands: ["sudo mount -a"]